apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: its-mitesh-kumar.github.io
  annotations:
    github.com/project-slug: its-mitesh-kumar/its-mitesh-kumar.github.io
spec:
  type: other
  lifecycle: unknown
  owner: user:default/its-mitesh-kumar
